source 'https://github.com/Tovema-iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!
platform :ios, 8.0

target 'PHUIKit_Example' do
  pod "TMUIKit", :path => "../"
    
    pod 'CYLDeallocBlockExecutor'
end
